### ISSUE TITLE
Blockquote style

### ISSUE THREAD

**Issue by hobbes7878** [The-Politico/django-politico-slackchat-renderer#11]
```css
.message .content blockquote:before {
    font-family: Times New Roman,serif;
    color: #bbb;
    content: "“";
    font-size: 60px;
    font-weight: 700;
    line-height: .1em;
    position: absolute;
    top: 23px;
    left: 2px;
}
```
